version: "3"
services:
  database:
    image : mongo
    container_name: 'mongodb-local'
    environment:
      - MONGO_INITDB_DATABASE=command-line
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    # volumes:
    #   - './init-mongod.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
    #   - './mongo-volume:/data/db'
    ports:
      - '27017:27017'
